const mainFunctions = require("./main");

module.exports = {
  // main Database
  // Document Db Object
  dbGetDocument: mainFunctions.dbGetDocument,
  dbCreateDocument: mainFunctions.dbCreateDocument,
  dbUpdateDocument: mainFunctions.dbUpdateDocument,
  dbDeleteDocument: mainFunctions.dbDeleteDocument,
  dbListDocuments: mainFunctions.dbListDocuments,
  createDocument: mainFunctions.createDocument,
  getIdListOfDocumentByField: mainFunctions.getIdListOfDocumentByField,
  getDocumentById: mainFunctions.getDocumentById,
  getDocumentAggById: mainFunctions.getDocumentAggById,
  getDocumentListByQuery: mainFunctions.getDocumentListByQuery,
  getDocumentStatsByQuery: mainFunctions.getDocumentStatsByQuery,
  getDocumentByQuery: mainFunctions.getDocumentByQuery,
  updateDocumentById: mainFunctions.updateDocumentById,
  updateDocumentByIdList: mainFunctions.updateDocumentByIdList,
  updateDocumentByQuery: mainFunctions.updateDocumentByQuery,
  deleteDocumentById: mainFunctions.deleteDocumentById,
  deleteDocumentByQuery: mainFunctions.deleteDocumentByQuery,
  // DocumentVersion Db Object
  dbGetDocumentversion: mainFunctions.dbGetDocumentversion,
  dbCreateDocumentversion: mainFunctions.dbCreateDocumentversion,
  dbUpdateDocumentversion: mainFunctions.dbUpdateDocumentversion,
  dbDeleteDocumentversion: mainFunctions.dbDeleteDocumentversion,
  dbListDocumentversions: mainFunctions.dbListDocumentversions,
  createDocumentVersion: mainFunctions.createDocumentVersion,
  getIdListOfDocumentVersionByField:
    mainFunctions.getIdListOfDocumentVersionByField,
  getDocumentVersionById: mainFunctions.getDocumentVersionById,
  getDocumentVersionAggById: mainFunctions.getDocumentVersionAggById,
  getDocumentVersionListByQuery: mainFunctions.getDocumentVersionListByQuery,
  getDocumentVersionStatsByQuery: mainFunctions.getDocumentVersionStatsByQuery,
  getDocumentVersionByQuery: mainFunctions.getDocumentVersionByQuery,
  updateDocumentVersionById: mainFunctions.updateDocumentVersionById,
  updateDocumentVersionByIdList: mainFunctions.updateDocumentVersionByIdList,
  updateDocumentVersionByQuery: mainFunctions.updateDocumentVersionByQuery,
  deleteDocumentVersionById: mainFunctions.deleteDocumentVersionById,
  deleteDocumentVersionByQuery: mainFunctions.deleteDocumentVersionByQuery,
  // FileObject Db Object
  dbGetFileobject: mainFunctions.dbGetFileobject,
  dbCreateFileobject: mainFunctions.dbCreateFileobject,
  dbUpdateFileobject: mainFunctions.dbUpdateFileobject,
  dbDeleteFileobject: mainFunctions.dbDeleteFileobject,
  dbListFileobjects: mainFunctions.dbListFileobjects,
  createFileObject: mainFunctions.createFileObject,
  getIdListOfFileObjectByField: mainFunctions.getIdListOfFileObjectByField,
  getFileObjectById: mainFunctions.getFileObjectById,
  getFileObjectAggById: mainFunctions.getFileObjectAggById,
  getFileObjectListByQuery: mainFunctions.getFileObjectListByQuery,
  getFileObjectStatsByQuery: mainFunctions.getFileObjectStatsByQuery,
  getFileObjectByQuery: mainFunctions.getFileObjectByQuery,
  updateFileObjectById: mainFunctions.updateFileObjectById,
  updateFileObjectByIdList: mainFunctions.updateFileObjectByIdList,
  updateFileObjectByQuery: mainFunctions.updateFileObjectByQuery,
  deleteFileObjectById: mainFunctions.deleteFileObjectById,
  deleteFileObjectByQuery: mainFunctions.deleteFileObjectByQuery,
  getFileObjectByIntegrityHash: mainFunctions.getFileObjectByIntegrityHash,
};
